### PR TITLE
Introduces versioned built artifacts

### PR DESCRIPTION
**Pull request by nkinkade**
This is one 1/3 of the changes necessary to implement versioned ePoxy images. It introduces a version string into the GCS path for all epoxy-images. In mlab-sandbox and mlab-staging, the version will always be simply "latest".

With one small exception, the version string comes from the `ImagesVersion` property for a node's GCD entity. The exception is one statically configured version path to the setup_k8s.sh script in GCS, which always points to "latest". This means that in production there will be a `latest/stage3_ubuntu/` directory containing nothing but this file. There is [an open issue](https://github.com/m-lab/k8s-support/issues/569) to resolve this.

To avoid breaking things during the transition to versioned images, the builds will continue to put all of the artifacts in their current locations. However, the changes in the PR should be released more or less simultaneously with the upcoming change to the ePoxy server.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/206)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/206)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[cloudbuild.yaml, line 67 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/206#-M_6rzpb6IXg4A1v8fQH:-M_6rzpb6IXg4A1v8fQI:b42xbhr) ([raw file](https://github.com/m-lab/epoxy-images/blob/37dc69732fd584e12a29c75648d1d7991650ce0b/cloudbuild.yaml#L67)):*
> ```YAML
>     '/workspace/output/stage3_initramfs_update.cpio.gz',
>     '/workspace/actions/stage2/stage1to2.ipxe',
>     '/workspace/actions/stage3_update/*.json',
> ```

It may be preferable to disable deploying unversioned artifacts so that the existing files continue to work as-is with the existing epoxy server.

The changes in this repo would over write the action scripts with ones that expect an image version.

It sounds like there are three things that needed to be updated in some order:

* epoxy-images
* epoxy-server
* epoxy datastore records

Ideally, the ordering would preserve functionality until later steps were completed. Do I understand correctly that overwriting the unversioned files would break existing behavior? What is the planned deployment order?

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/206)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[cloudbuild.yaml, line 67 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/206#-M_6rzpb6IXg4A1v8fQH:-M_7QvrP73ASg9lTTm55:be1w8wq) ([raw file](https://github.com/m-lab/epoxy-images/blob/37dc69732fd584e12a29c75648d1d7991650ce0b/cloudbuild.yaml#L67)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It may be preferable to disable deploying unversioned artifacts so that the existing files continue to work as-is with the existing epoxy server.

The changes in this repo would over write the action scripts with ones that expect an image version.

It sounds like there are three things that needed to be updated in some order:

* epoxy-images
* epoxy-server
* epoxy datastore records

Ideally, the ordering would preserve functionality until later steps were completed. Do I understand correctly that overwriting the unversioned files would break existing behavior? What is the planned deployment order?
</blockquote></details>

Not deploying unversioned artifacts is a good idea. That should take care of making epoxy-images safe to deploy at any time. I'll implement that now.

I haven't been overly concerned about deployment ordering because all of this is related to nodes rebooting, which only happens every 60 days, and we are fresh off a rolling reboot, so nodes won't reboot themselves for another 30 to 60 days. And Rebot reboots maybe a handful of nodes in a whole week. My assumption was that I'd be able to deploy the changes to the various repos over the course of a day or two, and not impact the booting of more than a couple nodes, at most. And even if those few nodes failed to boot, it wouldn't be a big deal because we have plenty of redundancy.

As we saw the other day, if I update the GCD entities to have the `ImagesVersion` field before ePoxy is update, then an error will be thrown about not being able to unmarshal that unknown prpperty into the Host struct. On the other hand, deploying ePoxy before the GCD entities are updated will likely also cause some sort of error, unless maybe I added a `json: "omitempty"` tag to the `ImagesVersion` field.

Otherwise, my thought had been to deploy in this order, somewhat arbitrarily:

* epoxy-images
* epoxy
* k8s-support
* update GCD entities manually with some sort of shell loop run from my local machine.
* Spot check a handful of nodes by rebooting them manually to be sure things are working as expected.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/206#-:-M_M3Uj16xASyeseMUuK:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[cloudbuild.yaml, line 67 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/206#-M_6rzpb6IXg4A1v8fQH:-M_M2lqx7bm2K93wX0Op:br3ymoi) ([raw file](https://github.com/m-lab/epoxy-images/blob/37dc69732fd584e12a29c75648d1d7991650ce0b/cloudbuild.yaml#L67)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Not deploying unversioned artifacts is a good idea. That should take care of making epoxy-images safe to deploy at any time. I'll implement that now.

I haven't been overly concerned about deployment ordering because all of this is related to nodes rebooting, which only happens every 60 days, and we are fresh off a rolling reboot, so nodes won't reboot themselves for another 30 to 60 days. And Rebot reboots maybe a handful of nodes in a whole week. My assumption was that I'd be able to deploy the changes to the various repos over the course of a day or two, and not impact the booting of more than a couple nodes, at most. And even if those few nodes failed to boot, it wouldn't be a big deal because we have plenty of redundancy.

As we saw the other day, if I update the GCD entities to have the `ImagesVersion` field before ePoxy is update, then an error will be thrown about not being able to unmarshal that unknown prpperty into the Host struct. On the other hand, deploying ePoxy before the GCD entities are updated will likely also cause some sort of error, unless maybe I added a `json: "omitempty"` tag to the `ImagesVersion` field.

Otherwise, my thought had been to deploy in this order, somewhat arbitrarily:

* epoxy-images
* epoxy
* k8s-support
* update GCD entities manually with some sort of shell loop run from my local machine.
* Spot check a handful of nodes by rebooting them manually to be sure things are working as expected.
</blockquote></details>

We talked in person. The main idea is that we will increasingly need to consider how to decompose functional changes into a sequence of small, safe changes rather than a single tightly-coupled change that could leave the system in an inconsistent state if an unexpected interruption prevents everything from happening at the right time.

The net result right now is that it should be possible to separate epoxy-images deployment from epoxy server deployment so they are not coupled. @nkinkade will continue to investigate whether the epoxy + datastore changes can be independent as well.
___
*[cloudbuild-stage1.yaml, line 49 at r2](https://reviewable.io/reviews/m-lab/epoxy-images/206#-M_M3O295zsVxdL5LQNK:-M_M3O295zsVxdL5LQNL:b-a9v6kk) ([raw file](https://github.com/m-lab/epoxy-images/blob/8e8ab1ce0f3df77f7c7d4a8e058d6e8e467dc930/cloudbuild-stage1.yaml#L49)):*
> ```YAML
>     '-h', 'Cache-Control:private, max-age=0, no-transform', '-m',
>     'cp', '-r', '/workspace/output/stage1_mlxrom/*',
>     'gs://epoxy-$PROJECT_ID/$_IMAGES_VERSION/stage1_mlxrom/'
> ```

If not already done -- the `$_IMAGES_VERSION` Cloud Build variable should be added to staging and prod ahead of time.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/206)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[cloudbuild-stage1.yaml, line 49 at r2](https://reviewable.io/reviews/m-lab/epoxy-images/206#-M_M3O295zsVxdL5LQNK:-M_MJnwb6xUDQOWDv6Rs:b-gum4cy) ([raw file](https://github.com/m-lab/epoxy-images/blob/8e8ab1ce0f3df77f7c7d4a8e058d6e8e467dc930/cloudbuild-stage1.yaml#L49)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If not already done -- the `$_IMAGES_VERSION` Cloud Build variable should be added to staging and prod ahead of time.
</blockquote></details>

Yup, I already added the `$_IMAGES_VERSION` custom substitution variables to the triggers in every project last week.

**Pull request merged**
