### PR TITLE
Add script to create a stage3_mlxupdate bootable ISO image

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a new command to create a bootable ISO image from the stage3 initramfs and vmlinuz images.

This script would be the last of three steps:

 * `setup_stage1.sh` -- which builds the mlx rom images
 * `setup_stage3_mlxupdate.sh` -- which builds an a custom initramfs with the mellanox firmware tools installed, so we can burn the mlx roms to the local NIC.
 * `create_update_iso.sh` -- which bundles the custom initramfs and kernel into a bootable image to initialize a system for the first time.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/14)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
@pboothe would you also take a look at this syntax: https://github.com/m-lab/epoxy-images/pull/14/files#diff-f77901f044c73321ed7841f78911df32R32 this is what I imagine the canonical epoxy network configuration looking like.

**Comment by pboothe** [comment]
That syntax LGTM

**Comment by gfr10598** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[create_update_iso.sh, line 30 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/14#-L2VuLmwONrFdFa7v1gm:-L2VuLmwONrFdFa7v1gn:bj8g14r) ([raw file](https://github.com/m-lab/epoxy-images/blob/ccb9170bd33efaf83f454765507ca124d2abc239/create_update_iso.sh#L30)):*
> ```Shell
> # Note: Strip the netmask and hard code it to /26 instead.
> ARGS+="epoxy.ip=${IPV4_ADDR%%/*}::${IPV4_GATEWAY}:255.255.255.192:${HOSTNAME}:"
> ARGS+="eth0:false:8.8.8.8:8.8.4.4 "
> ```

Should this be " ... ${DNS1}:${DNS2} " ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/14)*

**Comment by stephen-soltesz** [comment]
@gfr10598 Thank you, PTAL?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[create_update_iso.sh, line 30 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/14#-L2VuLmwONrFdFa7v1gm:-L2VvaaxxpRs7iXcCFD-:b-32ziq0) ([raw file](https://github.com/m-lab/epoxy-images/blob/ccb9170bd33efaf83f454765507ca124d2abc239/create_update_iso.sh#L30)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Should this be " ... ${DNS1}:${DNS2} " ?
</blockquote></details>

Oh, yes! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/14#-:-L2VvdLvrQSNvKiD6ZMK:b-g8cnbe)*

**Comment by gfr10598** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[create_update_iso.sh, line 24 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/14#-L2VvUlUmeMp4V_EoeLx:-L2VvUlUmeMp4V_EoeLy:b-w4zfg6) ([raw file](https://github.com/m-lab/epoxy-images/blob/ccb9170bd33efaf83f454765507ca124d2abc239/create_update_iso.sh#L24)):*
> ```Shell
> fi
> 
> # Disable interface naming by the kernel. Preserves the use of `eth0`, etc.
> ```

Add something like
ARGS are the extra kernel command line arguments that will be included in the isolinux.cfg.
They are interpreted by ... when the kernel boots.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/14)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/14#-:-L2Vwo9pRVXIvNVJLs2w:bnfp4nl)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[create_update_iso.sh, line 24 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/14#-L2VvUlUmeMp4V_EoeLx:-L2W-522-tGOUQb8XJwF:bcvjgzp) ([raw file](https://github.com/m-lab/epoxy-images/blob/ccb9170bd33efaf83f454765507ca124d2abc239/create_update_iso.sh#L24)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add something like
ARGS are the extra kernel command line arguments that will be included in the isolinux.cfg.
They are interpreted by ... when the kernel boots.
</blockquote></details>

Good idea. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/14)*

**Comment by stephen-soltesz** [comment]
The build break is unrelated to this PR. So, I'll submit this now and address the broken build separately.

**Pull request merged**
