### PR TITLE
Add custom_coreos command using Go pipe package

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change implements the `customize_coreos_pxe_image.sh` as a Go command line tool using a fork of the `pipe` package.

This is a demonstration of how we could start with bash scripts, and then migrate them to a Go command in such a way that we can provide unit tests.

The following should work ootb.
```
go get github.com/stephen-soltesz/epoxy-images/go/cmd/customize_coreos
cd $GOPATH/github.com/stephen-soltesz/epoxy-images/go/cmd/customize_coreos
~/bin/customize_coreos --custom $PWD/output/new.cpio.gz --initram file://$PWD/testdata/example.cpio.gz --vmlinuz file://$PWD/testdata/example.vmlinuz --resources $PWD/testdata/example.squashfs.addfiles/
```

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/10)

### CODE REVIEW

**Comment by pboothe** [comment]
High level: LGTM with one tiny comment. Lower level: I would like it if someone more experienced in Go idioms could check it out as well.

---

Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/cmd/customize_coreos/customize_coreos.go, line 9 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1rrePzu9cREnfT0qfM:-L1rreQ-MsGFU8QtvaZT:bi1cwia) ([raw file](https://github.com/m-lab/epoxy-images/blob/18b422f887d8d26ac958820dd977be587103b706/go/cmd/customize_coreos/customize_coreos.go#L9)):*
> ```Go
> 	"path/filepath"
> 
> 	flag "github.com/spf13/pflag"
> ```

Please use the regular flags package if you can.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-:-L1rusDRtkS7wFTzAPsJ:b-a0qzcb)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/cmd/customize_coreos/customize_coreos.go, line 9 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1rrePzu9cREnfT0qfM:-L1sNfTM9ncq4sJ1SVAa:b-896fix) ([raw file](https://github.com/m-lab/epoxy-images/blob/18b422f887d8d26ac958820dd977be587103b706/go/cmd/customize_coreos/customize_coreos.go#L9)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please use the regular flags package if you can.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/10)*

**Comment by stephen-soltesz** [comment]
@gfr10598 I elect you as someone more familiar with Go to comment on this approach to formalizing some operations that would otherwise need to be implemented using a bash script.

**Comment by gfr10598** [comment]
Reviewed 9 of 13 files at r1.
Review status: 9 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xRLUUp5GADNMoM22c:-L1xRLUUp5GADNMoM22d:b-42spnb) (no related file):*
Suggest you make the pipe changes into a PR in the fork, so they are easy to see.  I expect we will want to push this back upstream, or use a fork within m-lab sometime.

A few early comments.  Still working on more.

---

*[.travis.yml, line 31 at r2](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xSwex0s2otkoWS8t7:-L1xSwex0s2otkoWS8t8:b-yvsdhx) ([raw file](https://github.com/m-lab/epoxy-images/blob/19ea4e3aa53360303c4cae3bbe6fc2cf710307c8/.travis.yml#L31)):*
> ```YAML
> # Build stage2 vmlinuz image.
> # TODO: clean up args to setup_stage2.sh script.
> # NOTE: use travis_wait to allow build with no output for longer than 10m.
> ```

Obsolete note?

---

*[go/cmd/customize_coreos/customize_coreos.go, line 11 at r2](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xPmr5J6CUy9BzpzMh:-L1xPmr5J6CUy9BzpzMi:btmu8v3) ([raw file](https://github.com/m-lab/epoxy-images/blob/19ea4e3aa53360303c4cae3bbe6fc2cf710307c8/go/cmd/customize_coreos/customize_coreos.go#L11)):*
> ```Go
> 
> 	"github.com/stephen-soltesz/epoxy-images/go/shext"
> 	pipe "gopkg.in/stephen-soltesz/pipe.v3"
> ```

"pipe" is not necessary here.  The version number doesn't show up in the package import name.

---

*[go/cmd/customize_coreos/customize_coreos.go, line 22 at r2](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xTBpakcex_LXwyJr-:-L1xTBpbQPVTdWsYOI1Z:b-l046bi) ([raw file](https://github.com/m-lab/epoxy-images/blob/19ea4e3aa53360303c4cae3bbe6fc2cf710307c8/go/cmd/customize_coreos/customize_coreos.go#L22)):*
> ```Go
> 
> func init() {
> 	log.SetFlags(0)
> ```

Is this a no-op?

---

*[go/shext/testdata/test.squashfs, line 0 at r2](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xSOSoWWmqPIZBexnt:-L1xSOSpG66_cCLKZkqW:b242c97) ([raw file](https://github.com/m-lab/epoxy-images/blob/19ea4e3aa53360303c4cae3bbe6fc2cf710307c8/go/shext/testdata/test.squashfs#L0)):*
Since testdata has a lot of binary files, could you add a testdata/README.md that describes the test files?  In particular, how are the binary files generated?  Can they be generated programmatically and left out of git?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/10)*

**Comment by stephen-soltesz** [comment]
Review status: 9 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xRLUUp5GADNMoM22c:-L1xWaADIEW63DOrPttA:bb8jeuq) (no related file):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Suggest you make the pipe changes into a PR in the fork, so they are easy to see.  I expect we will want to push this back upstream, or use a fork within m-lab sometime.

A few early comments.  Still working on more.
</blockquote></details>

I don't object to creating a PR in principle, however the upstream is unchanged in 4 years -- https://github.com/go-pipe/pipe

I created an issue asking about a behavior that I encountered that I think is a mistake 10 days ago but have not heard back. And, I don't expect to.

I also expected that we'll want to fork this within m-lab. But, I think we're still in the "what do you think of this approach" stage.

What do you think of this approach?

---

*[.travis.yml, line 31 at r2](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xSwex0s2otkoWS8t7:-L1xTmymO5Stja70mqrl:bq6ytbf) ([raw file](https://github.com/m-lab/epoxy-images/blob/19ea4e3aa53360303c4cae3bbe6fc2cf710307c8/.travis.yml#L31)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Obsolete note?
</blockquote></details>

No. It should be a TODO, because this build typically takes ~8-9min but recently took longer than 10min and caused the build to fail b/c travis saw now output for 10m.

When I tried travis_wait it failed to preserve the quoted command passed to docker run. So, we'll need a different strategy. I'm not sure yet what the best approach is, possibly encapsulating more of this command into a secondary script (unfortunate), or implementing our own "travis_wait" function (differently unfortunate, but maybe better, and could be reusable for our other repos).

---

*[go/cmd/customize_coreos/customize_coreos.go, line 11 at r2](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xPmr5J6CUy9BzpzMh:-L1xVWgnRKa0Iv45wOco:bj26tg0) ([raw file](https://github.com/m-lab/epoxy-images/blob/19ea4e3aa53360303c4cae3bbe6fc2cf710307c8/go/cmd/customize_coreos/customize_coreos.go#L11)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

"pipe" is not necessary here.  The version number doesn't show up in the package import name.
</blockquote></details>

D'oh -- that's true, though it seems to confuse `goimports` which I have running on save. It removes the import since it doesn't see it used. I'm not sure how to preserve the convenience of `goimports`and the automatic package naming from go.

---

*[go/cmd/customize_coreos/customize_coreos.go, line 22 at r2](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xTBpakcex_LXwyJr-:-L1xUPhMs3YLSI04_Go5:b-tbr61x) ([raw file](https://github.com/m-lab/epoxy-images/blob/19ea4e3aa53360303c4cae3bbe6fc2cf710307c8/go/cmd/customize_coreos/customize_coreos.go#L22)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is this a no-op?
</blockquote></details>

`log.LstdFlags` is the default. This disables special logging prefixes entirely. The intention here was to generate output that mimics bash `set -x`.

---

*[go/shext/testdata/test.squashfs, line  at r2](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xSOSoWWmqPIZBexnt:-L1xUzDRQvSKa6Vifes_:b-3nttaj) ([raw file](https://github.com/m-lab/epoxy-images/blob/19ea4e3aa53360303c4cae3bbe6fc2cf710307c8/go/shext/testdata/test.squashfs#L)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Since testdata has a lot of binary files, could you add a testdata/README.md that describes the test files?  In particular, how are the binary files generated?  Can they be generated programmatically and left out of git?  
</blockquote></details>

I'm happy to do more here if we accept that using Go for composing script-like operations is a viable one and worthwhile in the long run.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/10)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 9 of 14 files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xRLUUp5GADNMoM22c:-L1xnbH7cSo8_ajS8Ef2:b5uqzq5) (no related file):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I don't object to creating a PR in principle, however the upstream is unchanged in 4 years -- https://github.com/go-pipe/pipe

I created an issue asking about a behavior that I encountered that I think is a mistake 10 days ago but have not heard back. And, I don't expect to.

I also expected that we'll want to fork this within m-lab. But, I think we're still in the "what do you think of this approach" stage.

What do you think of this approach?
</blockquote></details>

Got it.  I thought you were further along than "what do you think".
I didn't mean a PR for the upstream, I meant a separate branch in your fork, then merge into the master branch in your fork using a PR.  Then the PR is easy to look at to see what changed.

I guess next step then is to have a f2f discussion about whether we like this better than bash scripts?

---

*[go/cmd/customize_coreos/customize_coreos.go, line 22 at r2](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xTBpakcex_LXwyJr-:-L1xiuk-Xe8o3s24kuhc:bo3pjwk) ([raw file](https://github.com/m-lab/epoxy-images/blob/19ea4e3aa53360303c4cae3bbe6fc2cf710307c8/go/cmd/customize_coreos/customize_coreos.go#L22)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`log.LstdFlags` is the default. This disables special logging prefixes entirely. The intention here was to generate output that mimics bash `set -x`.
</blockquote></details>

Add comment?

---

*[go/cmd/customize_coreos/customize_coreos_test.go, line 24 at r3](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xjdpePe-vI7DDGk9L:-L1xjdpePe-vI7DDGk9M:b-82gegq) ([raw file](https://github.com/m-lab/epoxy-images/blob/4383485f0d29e9ddad0ba0dc7f873fc0376fc69e/go/cmd/customize_coreos/customize_coreos_test.go#L24)):*
> ```Go
> 			name: "working",
> 			args: args{
> 				vmlinuzURL: "testdata/example.vmlinuz",
> ```

Put the file:// here instead of adding it below?

---

*[go/cmd/customize_coreos/customize_coreos_test.go, line 41 at r3](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xjqTgoAkiwU3rjMtT:-L1xjqTgoAkiwU3rjMtU:bgrsgwe) ([raw file](https://github.com/m-lab/epoxy-images/blob/4383485f0d29e9ddad0ba0dc7f873fc0376fc69e/go/cmd/customize_coreos/customize_coreos_test.go#L41)):*
> ```Go
> 				path.Join("file://", cwd, tt.args.vmlinuzURL),
> 				path.Join("file://", cwd, tt.args.initramURL),
> 				path.Join(cwd, tt.args.resources),
> ```

Since you are using absPath, is the cwd necessary?

---

*[go/shext/customize_coreos_image.go, line 2 at r3](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xkCE9NLELMCA_Ngot:-L1xkCE9NLELMCA_Ngou:bicxqa2) ([raw file](https://github.com/m-lab/epoxy-images/blob/4383485f0d29e9ddad0ba0dc7f873fc0376fc69e/go/shext/customize_coreos_image.go#L2)):*
> ```Go
> // Package shext customize a coreos initram image.
> package shext
> ```

Why "shext"?  Doesn't convey meaning to me.

---

*[go/shext/customize_coreos_image_test.go, line 115 at r3](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xnE8v4hrPTf91FqKf:-L1xnE8v4hrPTf91FqKg:b9riy5j) ([raw file](https://github.com/m-lab/epoxy-images/blob/4383485f0d29e9ddad0ba0dc7f873fc0376fc69e/go/shext/customize_coreos_image_test.go#L115)):*
> ```Go
> 		output   string
> 	}
> 	tests := []struct {
> ```

BTW, I have a mild opinion that for single test cases, this repeated test structure makes the test harder to understand.  But it is tempered by the thought that using this template everywhere might make it seem normal and transparent after a while.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-:-L1xnyc3y-I_-TmzkdHd:bnfp4nl)*

**Comment by stephen-soltesz** [comment]
Review status: 9 of 15 files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xRLUUp5GADNMoM22c:-L26g5rNfSkNskziB2du:b-vka0ar) (no related file):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Got it.  I thought you were further along than "what do you think".
I didn't mean a PR for the upstream, I meant a separate branch in your fork, then merge into the master branch in your fork using a PR.  Then the PR is easy to look at to see what changed.

I guess next step then is to have a f2f discussion about whether we like this better than bash scripts?

</blockquote></details>

Yes, so we discussed in person and the consensus was that we basically liked this approach more than bash and more than python. So, I'll proceed with forking go-pipe into m-lab. And, I will add my changes via review to a new v3 branch. Then I'll circle back to these files to point them at the canonical package.

---

*[go/cmd/customize_coreos/customize_coreos.go, line 22 at r2](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xTBpakcex_LXwyJr-:-L271aRsbp_IGL_INGbP:b-896fix) ([raw file](https://github.com/m-lab/epoxy-images/blob/19ea4e3aa53360303c4cae3bbe6fc2cf710307c8/go/cmd/customize_coreos/customize_coreos.go#L22)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add comment?
</blockquote></details>

Done.

---

*[go/cmd/customize_coreos/customize_coreos_test.go, line 24 at r3](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xjdpePe-vI7DDGk9L:-L272OoIJOO7GQA6z6B0:bdso8gy) ([raw file](https://github.com/m-lab/epoxy-images/blob/4383485f0d29e9ddad0ba0dc7f873fc0376fc69e/go/cmd/customize_coreos/customize_coreos_test.go#L24)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Put the file:// here instead of adding it below?
</blockquote></details>

Good idea. I think I setup the absolute paths in the test args for the other tests. Early setup makes the call site clearer and simpler.

---

*[go/cmd/customize_coreos/customize_coreos_test.go, line 41 at r3](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xjqTgoAkiwU3rjMtT:-L274q_0NeHpqTwttfC4:bqrb7ar) ([raw file](https://github.com/m-lab/epoxy-images/blob/4383485f0d29e9ddad0ba0dc7f873fc0376fc69e/go/cmd/customize_coreos/customize_coreos_test.go#L41)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Since you are using absPath, is the cwd necessary?
</blockquote></details>

In `customize_coreos.go` `absPath` is used from `main()` on the parameters to `buildCustomImage`. Here I'm using `cwd` to construct an abspath. I could use that function here too, maybe.

---

*[go/shext/customize_coreos_image.go, line 2 at r3](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xkCE9NLELMCA_Ngot:-L275AhFwHDi-QBeYu_G:bnab2ld) ([raw file](https://github.com/m-lab/epoxy-images/blob/4383485f0d29e9ddad0ba0dc7f873fc0376fc69e/go/shext/customize_coreos_image.go#L2)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Why "shext"?  Doesn't convey meaning to me.
</blockquote></details>

¯\_(ツ)_/¯ 

"shell extension"?

That was my second best guess after rejecting "util" quickly during testing :-D

I intend for this package to include pre-packaged operations that might be "functions" if this were written in bash. Maybe the package could be called "operation", so call sites could look like `operation.Download()` or `operation.UnpackInitram()`? That might be a fancier word for "util" -- but each function should implement a self-contained "operation".

---

*[go/shext/customize_coreos_image_test.go, line 115 at r3](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xnE8v4hrPTf91FqKf:-L276oFzz1fHFYwTskgA:byns1an) ([raw file](https://github.com/m-lab/epoxy-images/blob/4383485f0d29e9ddad0ba0dc7f873fc0376fc69e/go/shext/customize_coreos_image_test.go#L115)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

BTW, I have a mild opinion that for single test cases, this repeated test structure makes the test harder to understand.  But it is tempered by the thought that using this template everywhere might make it seem normal and transparent after a while.
</blockquote></details>

So, this was also a way for me to experiment using VS Code for the first time and the "generate test code" function. I'm kind of excited by that.

My original thought was to have "working" and "not working" example cases. And, stopped trying to take this any further at some point.

I think you're right that if only one case can be tested, then the extra stuff is distracting. `TestUnpackInitram` may be an example of this.

Once we have a pipe version in m-lab I'll come back through and revise these tests to be multi-case or simplified for single-case. TODOs added.

---

*[go/shext/testdata/test.squashfs, line  at r2](https://reviewable.io:443/reviews/m-lab/epoxy-images/10#-L1xSOSoWWmqPIZBexnt:-L279F4ViFDHPsZITVYv:bhln47y) ([raw file](https://github.com/m-lab/epoxy-images/blob/19ea4e3aa53360303c4cae3bbe6fc2cf710307c8/go/shext/testdata/test.squashfs#L)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm happy to do more here if we accept that using Go for composing script-like operations is a viable one and worthwhile in the long run.
</blockquote></details>

Good idea. I'm inclined to document the steps to create them rather than writing new code to generate them.

I've also added a TODO for documenting this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/10)*

**Pull request merged**
