### PR TITLE
Sets CPU scaling governor to performance for all CPUs after boot.

### PR DESCRIPTION
**Pull request by nkinkade**
This PR is intended to resolve issue #190.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/191)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/191#-:-MLjOkiaApMZlFM-_PN1:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[configs/stage3_ubuntu/opt/mlab/bin/setup_after_boot.sh, line 23 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/191#-MLjOLXXA9U7LdFgDilr:-MLjOLXXA9U7LdFgDils:b-5yfemx) ([raw file](https://github.com/m-lab/epoxy-images/blob/c2096b3fce791a8aa2582d49cfe49809c1a0869a/configs/stage3_ubuntu/opt/mlab/bin/setup_after_boot.sh#L23)):*
> ```Shell
> # the OS default is "powersave".
> for cpu in /sys/devices/system/cpu/cpu[0-9]*; do
>   echo performance > $cpu/cpufreq/scaling_governor
> ```

I believe it probably does, but how do we know that this happens after the OS default is applied?

Is it possible to prevent the OS default from being applied by modifying the image build?

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/191)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[configs/stage3_ubuntu/opt/mlab/bin/setup_after_boot.sh, line 23 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/191#-MLjOLXXA9U7LdFgDilr:-MLjS6TV2NM4cqnbI1Wy:b-je4x7a) ([raw file](https://github.com/m-lab/epoxy-images/blob/c2096b3fce791a8aa2582d49cfe49809c1a0869a/configs/stage3_ubuntu/opt/mlab/bin/setup_after_boot.sh#L23)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I believe it probably does, but how do we know that this happens after the OS default is applied?

Is it possible to prevent the OS default from being applied by modifying the image build?
</blockquote></details>

It works. I tested it by booting mlab2-lga0t using the image built by this PR, then verified on mlab2-lga0t that the governor was "performance" for all CPUs. 

Your second question spurred me to look at why Ubuntu is setting the governor to "powersave" by default. Apparently, by default there is an enabled systemd unit called `ondemand.service`, which messes with the governor. In short, if it finds that "powersave" is a possible governor then it sets it to that for all CPUs. I believe that we should be able to disable that systemd service by default. And I verified on mlab1-lga0t that the there is a BIOS configuration for CPU performance which seems to have a default profile of "Performance".  Let me do some more experimenting tomorrow to see if we can disable this `ondemand.service` unit to get the desired outcome rather than this loop, which works, but is less clean that the former alternative.

**Review by stephen-soltesz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/191)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[configs/stage3_ubuntu/opt/mlab/bin/setup_after_boot.sh, line 23 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/191#-MLjOLXXA9U7LdFgDilr:-MLjUO8P-ZCmX5BBtAOx:b-p97rz7) ([raw file](https://github.com/m-lab/epoxy-images/blob/c2096b3fce791a8aa2582d49cfe49809c1a0869a/configs/stage3_ubuntu/opt/mlab/bin/setup_after_boot.sh#L23)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

It works. I tested it by booting mlab2-lga0t using the image built by this PR, then verified on mlab2-lga0t that the governor was "performance" for all CPUs. 

Your second question spurred me to look at why Ubuntu is setting the governor to "powersave" by default. Apparently, by default there is an enabled systemd unit called `ondemand.service`, which messes with the governor. In short, if it finds that "powersave" is a possible governor then it sets it to that for all CPUs. I believe that we should be able to disable that systemd service by default. And I verified on mlab1-lga0t that the there is a BIOS configuration for CPU performance which seems to have a default profile of "Performance".  Let me do some more experimenting tomorrow to see if we can disable this `ondemand.service` unit to get the desired outcome rather than this loop, which works, but is less clean that the former alternative.
</blockquote></details>

Thank you for investigating that! I agree it would be cleaner.

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: PTAL? I've removed my previous change in favor of disabling the ondemand.service during the stage3_ubuntu image build process. I rebooted mlab1-lga0t and the ondemand service was successfully disabled, and all CPUs were using the "performance" governor.

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/191#-:-MLnXwSDDB1FYDRJGF95:b-6t3jji)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

**Review by stephen-soltesz — APPROVED** [review]
Excellent! :lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/191#-:-MLnal5zCckliwAiUAia:bmphau4)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

**Review by stephen-soltesz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/191)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
