### PR TITLE
Add ePoxy stage2 image build scripts

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This PR adds initial support for building ePoxy stage2 images. Improvements are expected and planned.

Build instructions are included in the README. Ultimately, this will be automated through travis-ci.

We also include some binary source packages in a vendor directory. This approach is used to pin the versions and guarantee that they are available at build time.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/1)

### CODE REVIEW

**Comment by nkinkade** [comment]
Hi Stephen,

I've made a first pass over this.

Thanks!

Nathan

---

Reviewed 14 of 17 files at r1.
Review status: 14 of 17 files reviewed at latest revision, 13 unresolved discussions.

---

*[README.md, line 5 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcdPk8OKL8fdWVFxWa4:-KcdPk8OKL8fdWVFxWa5:bkymq2a) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/README.md#L5)):*
> ```Markdown
> Support for building Linux kernels, rootfs images, and ROMs for ePoxy
> 
> An ePoxy manged system depends on several image types:
> ```

s/manged/managed/

---

*[README.md, line 7 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcdPWI0QeztrNOEDwq2:-KcdPWI0QeztrNOEDwq3:b-y6vxkz) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/README.md#L7)):*
> ```Markdown
> An ePoxy manged system depends on several image types:
> 
>  * stage1 images that are either flashed to NICs, or burned to ISOs.
> ```

s/ISOs/CDs/

---

*[setup_stage2.sh, line 17 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcdTihAMV9f6y6azmVW:-KcdTihAMV9f6y6azmVX:b-bh3zux) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L17)):*
> ```Shell
> CONFIG_DIR=${3:?Error: Please specify absolute path to configuration directory}
> INITRAM_NAME=${4:?Error: Please specify absolute path of initramfs output file}
> KERNEL_NAME=${5:?Error: Please specify absolute path to vmlinuz output file}
> ```

Do the above have to be absolute paths? `readlink --canonicalize` below should resolve everything to an absolute path as necessary, right?

---

*[setup_stage2.sh, line 47 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcdlOCw4yHV-PMa5vUH:-KcdlOCw4yHV-PMa5vUI:bnv3qt4) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L47)):*
> ```Shell
>       exit 1
>     fi
>     tar xvf $tgz
> ```

The v[erbose] flag isn't needed here, is it?

---

*[setup_stage2.sh, line 63 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcdmhXZlXS_gIVdC80S:-KcdmhXZlXS_gIVdC80T:b98gcws) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L63)):*
> ```Shell
>   local config=$3
> 
>   if ! test -f $build/local/bin/busybox ; then
> ```

Where/when does the `local` subdirectory inside of `$build` get created? Is it just prerequisite that there must be a `local` directory inside whatever you pass for `$build`?

---

*[setup_stage2.sh, line 65 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-Kcdko9JfFxkixZS8iB5:-Kcdko9JfFxkixZS8iB6:b-pi0kgj) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L65)):*
> ```Shell
>   if ! test -f $build/local/bin/busybox ; then
>     pushd $build
>       unpack busybox-1.25.0 $vendor/busybox-1.25.0.tar.bz2
> ```

You're passing a tar-bizipped file to `unpack` here but it doesn't appear that `unpack` is prepared to handle compressed tar archives (tar is only getting flags `xf`). Also, if you plan to pass compressed files to `unpack` then will you also be passing it gzipped and bzipped files, such that it will have to decide whether to use the `j` or `z` flag?  Or have I just never understood that `tar` can automatically detect a compressed file and extract it for you?

Also, you are referencing a specific version number for the busybox archive.  Is this one of those cases where it would be clearer if the version of filename to be unpacked was passed in as a parameter? Doing that would push all information about versions and filenames into the `main()` which might make this easier to understand and update all in one place (for all of these packages). Just a thought.

---

*[setup_stage2.sh, line 200 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcdrpFKrazH7rIilNCZ:-KcdrpFLWkTO7BP_E3ow:b-ic7rp5) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L200)):*
> ```Shell
> 
>   echo "Compressing binaries"
>   mkdir -p $build_prefix/upx
> ```

Should this be `$install_prefix` instead of `$build_prefix`? Same below.... or change `local install_prefix=$1` to assign to `build_prefix`.

---

*[setup_stage2.sh, line 353 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcdzQ8BN1K_kZ-RL-Uz:-KcdzQ8BN1K_kZ-RL-V-:b2fvk9n) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L353)):*
> ```Shell
>   local kernel=$5
> 
>   # TODO: is there a better way to extract the base kernel version?
> ```

This won't give you precisely what you want, but it's close:

`apt-cache policy linux-source | grep Installed | awk '{print $2}'`

I could imagine that one might prefer parsing the output of the package management tools rather than relying on `ls | head -n 1` always returning the entry you want (though it likely will). The package management system just seems more authoritative and more deterministic. There is also output from `apt-cache show linux-source` and a few others.

Alternatively, it appears that you only ever use `$version` attached to `linux-source`, in which case this would give you the package name you want:

`apt-cache show linux-source | grep 'Depends:' | awk '{print $2}'`

---

*[setup_stage2.sh, line 411 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcduOPSZFJTdIMVxjaD:-KcduOPSZFJTdIMVxjaE:b5jt103) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L411)):*
> ```Shell
>   compress_binaries $BUILD_DIR/local \
>       bin/busybox \
>       bin/dropbearmulti \
> ```

Is `dropbearmulti` a build artifact of `build_dropbear()`? I'm not seeing where it gets created with this particular name.

---

*[simpleiso, line 20 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-Kce29qtjmYfokyTMtn8:-Kce29quAjMu1ew0pFCB:bl4d9eb) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/simpleiso#L20)):*
> ```
> # From the isolinux package.
> ISOLINUX_BIN=/usr/lib/ISOLINUX/isolinux.bin
> # From the syslinux-common package.
> ```

I don't see `syslinux-common` in the `apt-get` command in the Dockerfile. Is it installed by some other mechanism?

---

*[simpleiso, line 47 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-Kce39kNdMMHcv2MI39S:-Kce39kOgY637_AZYTG3:b8r5mwb) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/simpleiso#L47)):*
> ```
>       exit 0
>       ;;
>     i)
> ```

Should this option be `o)` instead?

---

*[simpleiso, line 61 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-Kce3uJ2CR9S3vkHmTyw:-Kce3uJ2CR9S3vkHmTyx:b-5crqe9) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/simpleiso#L61)):*
> ```
> # Assign positional parameters.
> VMLINUZ=${1:?Error: Please provide a vmlinuz image}
> ISO_NAME=${2:?Error: Please provide an ISO output file name}
> ```

The `help()` function indicates `vmlinuz` and `initramfs` as parameters one and two, respectively.  Is `initramfs` supposed to map to `ISO_NAME`? 

---

*[simpleiso, line 104 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-Kce4ZowT7cxRX6kzDFf:-Kce4ZowT7cxRX6kzDFg:b-hmz5qn) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/simpleiso#L104)):*
> ```
>   local isodir=$( mktemp -d /tmp/iso.dir.XXXXXX )
> 
>   setup_isofs $isodir $VMLINUZ "$INITRD" "${BOOT_PARAMS}"
> ```

If someone defined `BOOT_PARAMS` at the head of the file, but nothing for `INITRD`, would `setup_isofs()` assign `BOOT_PARAMS` to the local variable `initramfs`?

One tiny point of confusion is the name `INITRD` mapping to `initramfs`. Not a huge deal, but my understanding is that they are two different systems.  Might it be clearer if we use consistent naming?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-:-Kce8Ruh44PBh3CSf-um:b-m9pty7)*

**Comment by stephen-soltesz** [comment]
Hi, Nathan,

Thank you for the careful review!

PTAL?

---

Review status: 14 of 17 files reviewed at latest revision, 13 unresolved discussions.

---

*[README.md, line 5 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcdPk8OKL8fdWVFxWa4:-Kcoy7c5X2F8ColROsJb:b-896fix) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/README.md#L5)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

s/manged/managed/
</blockquote></details>

Done.

---

*[README.md, line 7 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcdPWI0QeztrNOEDwq2:-KcoyGnVoBENwTj8izTz:b-896fix) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/README.md#L7)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

s/ISOs/CDs/
</blockquote></details>

Done.

---

*[setup_stage2.sh, line 17 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcdTihAMV9f6y6azmVW:-KcpKcHmj73RAQ_pcBj0:byabe8m) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L17)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Do the above have to be absolute paths? `readlink --canonicalize` below should resolve everything to an absolute path as necessary, right?
</blockquote></details>

Right. I updated the help text.

---

*[setup_stage2.sh, line 47 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcdlOCw4yHV-PMa5vUH:-KcpGiNN83-h0VdT3kIM:b-kfvq2q) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L47)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

The v[erbose] flag isn't needed here, is it?
</blockquote></details>

Sometimes I like to see the files scroll by to convince me something is really happening :-) But, you're right it's not really needed. Removed.

---

*[setup_stage2.sh, line 63 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcdmhXZlXS_gIVdC80S:-KcpK9Wg-UW4BeJzoahG:b-2d8502) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L63)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Where/when does the `local` subdirectory inside of `$build` get created? Is it just prerequisite that there must be a `local` directory inside whatever you pass for `$build`?
</blockquote></details>

It's not a prerequisite. The `make install`creates `$build/local` -- this is the `BUSYBOX_INSTALL_DIR`. If busybox were a `configure` based system, then `$build/local` would be the install `--prefix`. 

---

*[setup_stage2.sh, line 65 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-Kcdko9JfFxkixZS8iB5:-KcpHWCO17-s5Dy9QNso:b-zgiag0) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L65)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

You're passing a tar-bizipped file to `unpack` here but it doesn't appear that `unpack` is prepared to handle compressed tar archives (tar is only getting flags `xf`). Also, if you plan to pass compressed files to `unpack` then will you also be passing it gzipped and bzipped files, such that it will have to decide whether to use the `j` or `z` flag?  Or have I just never understood that `tar` can automatically detect a compressed file and extract it for you?

Also, you are referencing a specific version number for the busybox archive.  Is this one of those cases where it would be clearer if the version of filename to be unpacked was passed in as a parameter? Doing that would push all information about versions and filenames into the `main()` which might make this easier to understand and update all in one place (for all of these packages). Just a thought.
</blockquote></details>

I think at one point tar required the caller to specify the compression format in the arguments. But, at some point it began supporting auto-discovery of the compression and only the `x` option is necessary.

Regarding the version numbers, yes. This is a good case to move the version numbers outside the function. Done.

---

*[setup_stage2.sh, line 200 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcdrpFKrazH7rIilNCZ:-KcpFhFRBQwiOU6LU2zH:bfu2mnd) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L200)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Should this be `$install_prefix` instead of `$build_prefix`? Same below.... or change `local install_prefix=$1` to assign to `build_prefix`.
</blockquote></details>

Good catch. Yes, fixed.

This was a last-minute docstring change that I failed to propagate through the rest of the function.

---

*[setup_stage2.sh, line 353 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcdzQ8BN1K_kZ-RL-Uz:-KcpENziNhrTjZreSEBI:b-7pzlq9) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L353)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

This won't give you precisely what you want, but it's close:

`apt-cache policy linux-source | grep Installed | awk '{print $2}'`

I could imagine that one might prefer parsing the output of the package management tools rather than relying on `ls | head -n 1` always returning the entry you want (though it likely will). The package management system just seems more authoritative and more deterministic. There is also output from `apt-cache show linux-source` and a few others.

Alternatively, it appears that you only ever use `$version` attached to `linux-source`, in which case this would give you the package name you want:

`apt-cache show linux-source | grep 'Depends:' | awk '{print $2}'`
</blockquote></details>

Ah! The `Depends` suggestion helped me find this approach:

    dpkg-query --show --showformat='${Depends}\n' linux-source

I think this is the winner. In particular, I think dpkg is querying installed packages while apt-cache is querying all possible packages. So, this limits the results to only installed package and that should mean the tar package is where we need it to be.

---

*[setup_stage2.sh, line 411 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcduOPSZFJTdIMVxjaD:-KcpCEG1p4c6DbiPedH0:b-sw95fz) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L411)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is `dropbearmulti` a build artifact of `build_dropbear()`? I'm not seeing where it gets created with this particular name.
</blockquote></details>

Good question. I've added a comment in `build_dropbear` to explain the `MULTI=1` value.

---

*[simpleiso, line 20 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-Kce29qtjmYfokyTMtn8:-KcozaUeo7UfVr6wmFVG:b2bmg4o) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/simpleiso#L20)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I don't see `syslinux-common` in the `apt-get` command in the Dockerfile. Is it installed by some other mechanism?
</blockquote></details>

Good question. isolinux depends on syslinux-common and pulls it in automatically.

---

*[simpleiso, line 47 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-Kce39kNdMMHcv2MI39S:-Kcp-55HelACcUcblaCz:b-qs3ids) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/simpleiso#L47)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Should this option be `o)` instead?
</blockquote></details>

I updated how positional parameters are processed but forgot to update the help text.

It should be that the kernel and output filename are required parameters. And, the extra kernel boot parameters and an initramfs file are optional.

Fixed.

---

*[simpleiso, line 61 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-Kce3uJ2CR9S3vkHmTyw:-Kcp-IcxGu4zj4XxBEj7:bpm56qd) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/simpleiso#L61)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

The `help()` function indicates `vmlinuz` and `initramfs` as parameters one and two, respectively.  Is `initramfs` supposed to map to `ISO_NAME`? 
</blockquote></details>

The help text should be consistent with the positional parameters now.

---

*[simpleiso, line 104 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-Kce4ZowT7cxRX6kzDFf:-Kcp0a4DuvV81dLxDfk4:b-1xs028) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/simpleiso#L104)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

If someone defined `BOOT_PARAMS` at the head of the file, but nothing for `INITRD`, would `setup_isofs()` assign `BOOT_PARAMS` to the local variable `initramfs`?

One tiny point of confusion is the name `INITRD` mapping to `initramfs`. Not a huge deal, but my understanding is that they are two different systems.  Might it be clearer if we use consistent naming?
</blockquote></details>

Good questions.

Regarding passing parameters to `setup_isofs`, the quotes around each parameter at the call site handles the case when `INITRD` is empty and `BOOT_PARAMS` is not.

```
function use_args() {
  local required1=$1
  local required2=$2
  local optional1=$3
  local optional2=$4

  echo "required1: $required1"
  echo "required2: $required2"
  echo "optional1: $optional1"
  echo "optional2: $optional2"
}
```
Outputs:
```
ARG1=
ARG2=test
use_args /tmp/foo vmlinuz "$ARG1" "$ARG2" 

required1: /tmp/foo
required2: vmlinuz
optional1: 
optional2: test
```

Without the quotes, the empty parameter is not where we want it:
```
ARG1=
ARG2=test
use_args /tmp/foo vmlinuz $ARG1 $ARG2

required1: /tmp/foo
required2: vmlinuz
optional1: test
optional2: 
```

Regarding the names `INITRD` and `initramfs` -- you're right that they're different things. Unfortunately, the terms are often used interchangeably (which predisposes me to use them interchangably). And, the kernel even auto-detects things during boot making the formats interchangeable in practice.

Consistency is a good suggestion. So, for consistency, I've updated this script to use "initramfs" or "INITRAMFS" throughout where possible. Though, syslinux only supports the one keyword for "INITRD."

My understanding is informed by this piece of kernel documentation. https://www.kernel.org/doc/Documentation/filesystems/ramfs-rootfs-initramfs.txt

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-:-KcpUfGnWcLHAJCvDbPM:b-5ncl1m)*

**Comment by nkinkade** [comment]
Only one tiny question remaining. I thought for a second there was going to be no round 2. And it may even be that we don't need a round 2 and that my question isn't a problem.

---

Reviewed 2 of 3 files at r2.
Review status: 16 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[setup_stage2.sh, line 65 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-Kcdko9JfFxkixZS8iB5:-Kcxyp_OL6V3LKF2vWIq:buox5sy) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L65)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I think at one point tar required the caller to specify the compression format in the arguments. But, at some point it began supporting auto-discovery of the compression and only the `x` option is necessary.

Regarding the version numbers, yes. This is a good case to move the version numbers outside the function. Done.
</blockquote></details>

That is good to know about `tar`! I never realized that `tar` was smart enough to figure out a) that the tar archive was compressed b) that it could figure out a) and then automatically select the right tool for decompressing the archive. 

---

*[setup_stage2.sh, line 411 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-KcduOPSZFJTdIMVxjaD:-Kcy-Pyn4HlQo7lBTf-7:bqevvlv) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/setup_stage2.sh#L411)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Good question. I've added a comment in `build_dropbear` to explain the `MULTI=1` value.
</blockquote></details>

Thanks. That comment now makes it clear where `dropbearmulti` is coming from.

---

*[simpleiso, line 47 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-Kce39kNdMMHcv2MI39S:-Kcy-oM6LJ-XWjCJBTtf:b-99ceho) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/simpleiso#L47)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I updated how positional parameters are processed but forgot to update the help text.

It should be that the kernel and output filename are required parameters. And, the extra kernel boot parameters and an initramfs file are optional.

Fixed.
</blockquote></details>

`while getops` still refers to `ho:x:`. Should that be `hi:x:`?

---

*[simpleiso, line 104 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-Kce4ZowT7cxRX6kzDFf:-Kcy0RexZ4pk8FdWtrCh:blmkcdq) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/simpleiso#L104)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Good questions.

Regarding passing parameters to `setup_isofs`, the quotes around each parameter at the call site handles the case when `INITRD` is empty and `BOOT_PARAMS` is not.

```
function use_args() {
  local required1=$1
  local required2=$2
  local optional1=$3
  local optional2=$4

  echo "required1: $required1"
  echo "required2: $required2"
  echo "optional1: $optional1"
  echo "optional2: $optional2"
}
```
Outputs:
```
ARG1=
ARG2=test
use_args /tmp/foo vmlinuz "$ARG1" "$ARG2" 

required1: /tmp/foo
required2: vmlinuz
optional1: 
optional2: test
```

Without the quotes, the empty parameter is not where we want it:
```
ARG1=
ARG2=test
use_args /tmp/foo vmlinuz $ARG1 $ARG2

required1: /tmp/foo
required2: vmlinuz
optional1: test
optional2: 
```

Regarding the names `INITRD` and `initramfs` -- you're right that they're different things. Unfortunately, the terms are often used interchangeably (which predisposes me to use them interchangably). And, the kernel even auto-detects things during boot making the formats interchangeable in practice.

Consistency is a good suggestion. So, for consistency, I've updated this script to use "initramfs" or "INITRAMFS" throughout where possible. Though, syslinux only supports the one keyword for "INITRD."

My understanding is informed by this piece of kernel documentation. https://www.kernel.org/doc/Documentation/filesystems/ramfs-rootfs-initramfs.txt
</blockquote></details>

Thanks for the explanation of the positional parameters. That is very helpful, and I did not know that you could put quotes around a passed parameter to help enforce its position.

Re: initrd vs initramfs: understood and thanks for the clarification

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-:-Kcy0ux_UaH-lKWE1NYB:b-hmh1xi)*

**Comment by stephen-soltesz** [comment]
Review status: 16 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[simpleiso, line 47 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-Kce39kNdMMHcv2MI39S:-Kcy4phyvGnjCY8MtsOy:b-k2rwtz) ([raw file](https://github.com/m-lab/epoxy-images/blob/06014689c40ef867d3e2d5ad60526013d0660d52/simpleiso#L47)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

`while getops` still refers to `ho:x:`. Should that be `hi:x:`?
</blockquote></details>

Good catch. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/1)*

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-:-Kcy8ksxA8C9vke2bmi8:bnfp4nl)*

**Comment by stephen-soltesz** [comment]
Thank you for the review!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/1#-:-KcyPMgH2r_Xhijo3NAN:b-rrkdbt)*

**Pull request merged**
