### PR TITLE
Automatically create the control plane, when it doesn't already exist

### PR DESCRIPTION
**Pull request by nkinkade**
Important note: this PR depends on numerous [changes in the terraform-support repository](https://github.com/m-lab/terraform-support/compare/sandbox-kinkade) which have not yet been submitted for review, nor are the changes yet cohesively organized into the existing code in the main branch. Notably, instance creation in terraform-support is now responsible for adding various metadata to instances, which some of the scripts in this PR take advantage of.

Additionally, this PR includes systemd services and accompanying shell scripts to do things like:

* Have GCP-internal VMs (not control plane) join the cluster (e.g., the Prometheus VM)
* Mount the persistent data volume on GCP-internal VMs
* Mount the persistent data volume on control plane nodes

This PR is somewhat large. I'm happy to go over the changes on a VC.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/234)

### CODE REVIEW

**Comment by nkinkade** [comment]
I apologize about this, but FYI that I have made additional commits to this PR branch since we last reviewed it together on the Open VC. They are changes arising from my experiment today of blowing away the entire sandbox cluster and recreating it with nothing more than the Packer images created by this PR, plus Terraform configs. Certain shortcomings didn't come to my attention until I did this exercise, resulting in additional commits to this PR. There may still be a few more to come, but it shouldn't be many (crossing fingers).

**Review by stephen-soltesz — COMMENTED** [review]
I'm looking closely now.

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/234#-:-NNgfasN1w1u8Jux9osV:b-oss0xm)* status: 0 of 1 approvals obtained

**Review by nkinkade — COMMENTED** [review]
Thank you for the review. I have made a few commits to address issues you brought up, and attempted to answer a few questions. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/234#-:-NNhWnvF4EKH1okYmyFU:bcvx03f)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cloudbuild.yaml` line 4 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNgg5EE7_t3lSiz2EhO:-NNhOWf70ZmIn3BY05kv:b-803clc) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/cloudbuild.yaml#L4)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

iiuc, the default `diskSizeGb:` is now used here and in cloudbuild-packer. Just checking, was 400GB wildly too big before? or do both of these fit within 100GB each?
</blockquote></details>

400GB was mostly for stage1 builds, since the stage1 builds are creating hundreds of ~500MB ISO images. I've removed the increased disk size here (stage3 builds), since stage3 builds should easily fit within the default of 100GB, with load of room to spare. The timeout could be drastically reduced for this build as well, but I left it alone because its not hurting anything.  A disk of 400GB wasn't necessarily hurting anything either, but I figured that it might cause our builds to be a bit more costly, so I chose to reduce that one thing.
___
*[`configs/virtual_ubuntu/etc/systemd/system/token-server.service` line 19 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNhJXua9RbzPYHKdHNx:-NNhQe0aA8Elj3akEzXN:b-c80wj4) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/configs/virtual_ubuntu/etc/systemd/system/token-server.service#L19)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Should this also depend on `mount-data-api.service`  to ensure this path exists?
</blockquote></details>

I think you are right. I have added an `After` and `Requires` for `mount-data-api.service` for this service (token-server.service).
___
*[`configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh` line 15 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNgpoSW-RyTG-NsX7xo:-NNhQtJr7tPxTexcjJcK:b-8etji8) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh#L15)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Clarifying: terraform sets this metadata?

If this is not written elsewhere, would you be willing to sketch the high-level idea encoded here? 

https://docs.google.com/document/d/12hwiaWJGqnwUB9zjxmSvw9wf8gFycdPZnPV6iqIjHMc/edit
</blockquote></details>

That is correct, Terraform adds the `cluster_data` metadata field to the control plane instances:

https://github.com/m-lab/terraform-support/blob/main/mlab-sandbox/platform-cluster/instances.tf#L88

I will update that document with implementation details.
___
*[`configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh` line 146 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNhCwxu9kHtZiu-Iukh:-NNhRNcQ5J2GOP25KJTO:b-tv62zc) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh#L146)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Ah, so there are multiple writers to the metadata service. A simple diagram could clarify the relationship between TF, metadata, the first node, and subsequent nodes.
</blockquote></details>

Yes, that is correct. The `cluster_data` metadata field is added to the control plane nodes by Terraform.  In this script one additional field is added to `cluster_attributes`, which is only used by the remaining two control plane nodes that need to join the cluster. Once the cluster is initialized, this `cert_key` attributes is no longer used, and will get overwritten by the next `terraform apply`. I will document this is the Terraforming M-Lab document.
___
*[`configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh` line 164 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNhFuiN3ephy9jsUoaq:-NNhRwkn31wzpxxCgOsf:b-tk3v50) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh#L164)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just clarifying, this is project-level scope metadata, so this would prevent (for example) hosting more than one cluster per GCP project?
</blockquote></details>

Yes, this is project metadata, not instance metadata. The name is `platform_cluster_ca_hash`, which shouldn't collide with any other name, since presumably we will only ever run a single platform cluster. If we do for some reason run multiple platform clusters, then we can simply rename the metadata field appropriately so that it is unique for each cluster. e.g., `platform_cluster_1_ca_hash`, etc.
___
*[`configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh` line 183 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNhGxVf-PX8sjJOxf6i:-NNhSSyqBmP7duVV-Tes:b-511m8s) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh#L183)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: DaemonSet
</blockquote></details>

In this case it is actually DaemonSets plural, because we are deploying both the `flannel-physical` and `flannel-virtual` DaemonSets, which are two distinct DaemonSets.
___
*[`configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh` line 184 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNhH2D1-hY1N-nnlck2:-NNhSnkQAQGs2otLbCSE:bt2vr1b) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh#L184)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: come
</blockquote></details>

Fixed.
___
*[`configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh` line 189 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNhHM0gEXL4w7gELAd6:-NNhSwsiAZQYuGmqMyvT:b1j2sj5) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh#L189)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm, we pulling authoritative information from a few sources. terraform-support, k8s-support, metadata server at runtime.
</blockquote></details>

It's true that we are pulling authoritative information here:

* k8s-support: k8s-support is (currently) the authoritative place for all k8s workload configuration.
* GCP project/instance metadata: it feels like we are using the metadata server in the intended an appropriate fashion?
 
But are we pulling information from terraform-support in this repo? terraform-support is responsible for injecting certain metadata into instances (not projects), but after that it seems to me that there is only reading metadata. This script doesn't reference or obtain any information from the terraform-support repo.
___
*[`configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh` line 190 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNhI32M6J1iOPbjyIWq:-NNhU2Zz1JqO12sCcCaq:b-shs4my) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh#L190)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

In principle could these configs and daemonset configs be part of this image? These are logically part of the cluster?
</blockquote></details>

They could, I believe, but something seems awkward to me about separating the cluster workload configurations and deployments into two separate repos. Additionally, the flannel DaemonSets are not GCP resources. Software deployment and configuration steps are generally not supposed to be part of your Terraform configs, if I understand the best-practices recommendations. Terraform does include mechanisms to do provisioning after a resource is created, but I believe it is generally discouraged, unless you absolutely cannot avoid it.
___
*[`configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh` line 286 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNhKR320h9hmmc-calE:-NNhV73Q7tXcaUz8iZbO:b66ci7h) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh#L286)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

These config changes take effect automatically?
</blockquote></details>

Yes. The kubelet has a `StaticPodPath` configuration that it watches (kubeadm sets this up for us). Whenever it see changes in that directory it will automatically deploy the new workload, or restart an existing one.

https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/#static-pod-creation
___
*[`configs/virtual_ubuntu/opt/mlab/bin/mount-data-api.sh` line 29 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNgkJDWDaZ0TkJAqSym:-NNhVkxV3sJPbiF8qgw9:b8ygkh0) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/configs/virtual_ubuntu/opt/mlab/bin/mount-data-api.sh#L29)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What happens if `${dev_name}` is undefined?
</blockquote></details>

I don't know. Possibly it would create `/dev/disk/by-id/google-`? I've added a check that will fail the script if `${dev_name}` doesn't exist.

**Review by stephen-soltesz — COMMENTED** [review]
So much bash.

Some small comments/questions.

I still don't have a sharp picture of how configuration information flows through our repos, or which depend on others.

I think things basically, lgtm.

> Reviewed 10 of 17 files at r1, 4 of 7 files at r2, 5 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/234#-:-NP3Z9aG4FpdiCOo_Rlr:bexre9d)* status: 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`configs/stage3_ubuntu/etc/systemd/system/write-metadata.service` line 9 at r4](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NP3PIHhDLqe7tuXKonD:-NP3PIHhDLqe7tuXKonE:b-47wku4) ([raw file](https://github.com/m-lab/epoxy-images/blob/680b5a31ff059497b8606b97521be2d6c363d754/configs/stage3_ubuntu/etc/systemd/system/write-metadata.service#L9)):*
> ```desktop
> # hostname value to the metadata directory, then be sure this unit runs later,
> # otherwise we get some randomish looking string for the hostname.
> After=generate-eth0-config.service
> ```

I can't find this file. Is this ours?
___
*[`configs/stage3_ubuntu/opt/mlab/bin/write-metadata.sh` line 21 at r4](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NP3PVqaAMowyFXwICCm:-NP3PVqaAMowyFXwICCn:b-h44kle) ([raw file](https://github.com/m-lab/epoxy-images/blob/680b5a31ff059497b8606b97521be2d6c363d754/configs/stage3_ubuntu/opt/mlab/bin/write-metadata.sh#L21)):*
> ```Shell
> # physical and virtual nodes will this metadata file to provide a common
> # interface for uuid-annotator.
> hostname | tr -d '\n' > $METADATA_DIR/node-name
> ```

Just clarifying, is the description still applicable? I don't object to saving this value in the metadata dir, but my understanding is that the docstring is out of sync.
___
*[`configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh` line 189 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNhHM0gEXL4w7gELAd6:-NP3_pu033j1U8Je1xKU:b-4b3fmx) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh#L189)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

It's true that we are pulling authoritative information here:

* k8s-support: k8s-support is (currently) the authoritative place for all k8s workload configuration.
* GCP project/instance metadata: it feels like we are using the metadata server in the intended an appropriate fashion?
 
But are we pulling information from terraform-support in this repo? terraform-support is responsible for injecting certain metadata into instances (not projects), but after that it seems to me that there is only reading metadata. This script doesn't reference or obtain any information from the terraform-support repo.
</blockquote></details>

I'm trying to build a high-level picture how things fit together. Is this correct?

* terraform-support - includes definitions for GCP regions of the VMs in the control plane, and all virtual nodes.
* k8s-support - includes a mirror of some of this information, with some additional information about the cluster and core service versions.
* metadata server - includes coordination data between each of the control plane nodes (as they start up), some information between service nodes and the control plane, e.g. CA certs.
___
*[`configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh` line 190 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNhI32M6J1iOPbjyIWq:-NP3Zmk28xhtxAHbvBAK:b-r5t8bh) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh#L190)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

They could, I believe, but something seems awkward to me about separating the cluster workload configurations and deployments into two separate repos. Additionally, the flannel DaemonSets are not GCP resources. Software deployment and configuration steps are generally not supposed to be part of your Terraform configs, if I understand the best-practices recommendations. Terraform does include mechanisms to do provisioning after a resource is created, but I believe it is generally discouraged, unless you absolutely cannot avoid it.
</blockquote></details>

Okay. Is this the division of responsibility?

* terraform-support - provisions the resources (VMs, LBs) the scripts/images from this PR depend on (epoxy-images for virtual nodes).
* epoxy-images for virtual nodes - provisions the k8s cluster (and nodes).
* k8s-support - provisions services running on the cluster.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/234)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`configs/stage3_ubuntu/etc/systemd/system/write-metadata.service` line 9 at r4](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NP3PIHhDLqe7tuXKonD:-NP3c-at6zSKoIlELMPK:bi3r3nz) ([raw file](https://github.com/m-lab/epoxy-images/blob/680b5a31ff059497b8606b97521be2d6c363d754/configs/stage3_ubuntu/etc/systemd/system/write-metadata.service#L9)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I can't find this file. Is this ours?
</blockquote></details>

It is ours. It is a standard systemd service that we include on physical machines:

https://github.com/m-lab/epoxy-images/blob/main/configs/stage3_ubuntu/etc/systemd/system/generate-eth0-config.service

Among other things, that service changes the system hostname to the one we recognize.
___
*[`configs/stage3_ubuntu/opt/mlab/bin/write-metadata.sh` line 21 at r4](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NP3PVqaAMowyFXwICCm:-NP3cvBu0IOnjVPaHs4L:b-4wclli) ([raw file](https://github.com/m-lab/epoxy-images/blob/680b5a31ff059497b8606b97521be2d6c363d754/configs/stage3_ubuntu/opt/mlab/bin/write-metadata.sh#L21)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just clarifying, is the description still applicable? I don't object to saving this value in the metadata dir, but my understanding is that the docstring is out of sync.
</blockquote></details>

You're right, the description is out of date. Indeed, the need to write the hostname to a file isn't even required any longer. I was going to leave it, just in case down the road we found some use case for wanting it there. Instead, I have opted to remove writing the hostname to a file in both this file, as well as the same script for virtual nodes.
___
*[`configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh` line 189 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNhHM0gEXL4w7gELAd6:-NP3dSnADMLRYRoSrdmK:blxpat7) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh#L189)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm trying to build a high-level picture how things fit together. Is this correct?

* terraform-support - includes definitions for GCP regions of the VMs in the control plane, and all virtual nodes.
* k8s-support - includes a mirror of some of this information, with some additional information about the cluster and core service versions.
* metadata server - includes coordination data between each of the control plane nodes (as they start up), some information between service nodes and the control plane, e.g. CA certs.
</blockquote></details>

That seems about right.  It is a good, and correct, observation that we are currently duplicating some configuration information between terraform-support and k8s-support. Principally, I believe, the zones and regions of control plane machines. Once we have fully migrated to Terraform and have no dependency on most of the "bootstrap" scripts in k8s-support, then I believe most of the duplication would only be superficial and could be safely removed the k8s_deploy.conf file.

However, today, the script `upgrade_api_cluster.sh` in k8s-support is still the way to upgrade the API cluster to a new version of k8s, and it needs some of that zone/region information. That said, I feel pretty confident that we can at some point migration everything to Terraform, at which point k8s-support will be purely about workloads.

I think ideally, terraform-support will be about creating the cloud infrastructure, and k8s-support will be about deploying services to the cluster, and k8s-support will not care about zones and regions, etc., which it largely doesn't today, except for upgrade and maintenance.

Regarding the metadata server, the plan is to continue using it to share some data between control plane nodes, but just today I submitted a PR for the token_server, which implements a v2 endpoint, which will return the CA cert hash _and_ the API load balancer name. Today (in sandbox) these two things are stored in project metadata, but my hope is that soon it won't be, and nodes will get that data from epoxy/token_server.
___
*[`configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh` line 190 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNhI32M6J1iOPbjyIWq:-NP3fsviCJKyenR3e8eQ:b20jad5) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh#L190)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Okay. Is this the division of responsibility?

* terraform-support - provisions the resources (VMs, LBs) the scripts/images from this PR depend on (epoxy-images for virtual nodes).
* epoxy-images for virtual nodes - provisions the k8s cluster (and nodes).
* k8s-support - provisions services running on the cluster.


</blockquote></details>

That seems about right. In slightly different words:

* terraform-support: provision all cloud resources, with little to no configuration.
* epoxy-images: provision images for all machines to boot (physical and virtual), which would include self-organizing functions like (configure network interfaces, deploy the k8s control plane (if it doesn't already exist), including critical binaries (kubeadm, kubelet, containerd, crictl, etc.).
* k8s-support: configure and deploy workloads to an existing cluster.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/234#-:-NP3v6TB1qM3oYEJpeZ-:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[`configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh` line 189 at r3](https://reviewable.io/reviews/m-lab/epoxy-images/234#-NNhHM0gEXL4w7gELAd6:-NP3uhF95J4S0V8P3Yeo:broflaw) ([raw file](https://github.com/m-lab/epoxy-images/blob/ade19d8baeccaebcad3b2dff11785b0c6750c42a/configs/virtual_ubuntu/opt/mlab/bin/create-control-plane.sh#L189)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

That seems about right.  It is a good, and correct, observation that we are currently duplicating some configuration information between terraform-support and k8s-support. Principally, I believe, the zones and regions of control plane machines. Once we have fully migrated to Terraform and have no dependency on most of the "bootstrap" scripts in k8s-support, then I believe most of the duplication would only be superficial and could be safely removed the k8s_deploy.conf file.

However, today, the script `upgrade_api_cluster.sh` in k8s-support is still the way to upgrade the API cluster to a new version of k8s, and it needs some of that zone/region information. That said, I feel pretty confident that we can at some point migration everything to Terraform, at which point k8s-support will be purely about workloads.

I think ideally, terraform-support will be about creating the cloud infrastructure, and k8s-support will be about deploying services to the cluster, and k8s-support will not care about zones and regions, etc., which it largely doesn't today, except for upgrade and maintenance.

Regarding the metadata server, the plan is to continue using it to share some data between control plane nodes, but just today I submitted a PR for the token_server, which implements a v2 endpoint, which will return the CA cert hash _and_ the API load balancer name. Today (in sandbox) these two things are stored in project metadata, but my hope is that soon it won't be, and nodes will get that data from epoxy/token_server.
</blockquote></details>

I like the vision for how to evolve things over time. :+1:

Please write this down, maybe in the "Terraforming M-lab" doc? Something to track so we know when we've reached this future end state.

**Pull request merged**
