### PR TITLE
An initial stab at putting things in the right place

### PR DESCRIPTION
**Pull request by pboothe**
Set up the binaries as part of the image and not the ePoxy action.

Part of https://github.com/m-lab/k8s-support/issues/28

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/52)

### CODE REVIEW

**Comment by pboothe** [comment]
https://github.com/m-lab/k8s-support/pull/30 removes the binary setup from the epoxy action.

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[setup_stage3_coreos.sh, line 6 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/52#-LC4ChI8DL8jtjGQuxKp:-LC4ChI8DL8jtjGQuxKq:byzsoos) ([raw file](https://github.com/m-lab/epoxy-images/blob/0f675ac4f20b3a045bae579b348a472d54055cae/setup_stage3_coreos.sh#L6)):*
> ```Shell
> # modified image that embeds custom scripts and static cloud-config.yml. These
> # custom scripts conigure the static network IP and allow for running a
> # post-boot setup script.
> ```

Please also note that we install dependencies for the current stable version of kubeadm (or k8s?)

---

*[setup_stage3_coreos.sh, line 53 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/52#-LC4D9OPCH-JO2zxMcdc:-LC4D9OQ0928rok9KV-D:b-yabayz) ([raw file](https://github.com/m-lab/epoxy-images/blob/0f675ac4f20b3a045bae579b348a472d54055cae/setup_stage3_coreos.sh#L53)):*
> ```Shell
>   # TODO: calico
> 
>   # Container networking interface
> ```

Please use complete sentences in comments. I think I've inherited this bias from Go.

---

*[setup_stage3_coreos.sh, line 56 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/52#-LC4DmAs8K95j5KNL6Z4:-LC4DmAs8K95j5KNL6Z5:b3oqgvp) ([raw file](https://github.com/m-lab/epoxy-images/blob/0f675ac4f20b3a045bae579b348a472d54055cae/setup_stage3_coreos.sh#L56)):*
> ```Shell
>   mkdir -p squashfs-root/cni/bin
>   CNI_VERSION="v0.6.0"
>   curl -L "https://github.com/containernetworking/plugins/releases/download/${CNI_VERSION}/cni-plugins-amd64-${CNI_VERSION}.tgz" | tar -C squashfs-root/cni/bin -xz
> ```

This is a nit -- I still think long name parameters for less common options help readability. In this case `--location --show-error --silent` for curl and `--directory` for tar.

---

*[setup_stage3_coreos.sh, line 62 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/52#-LC4Efvq7VhvCd4p0A5i:-LC4Efvq7VhvCd4p0A5j:b-ymphnh) ([raw file](https://github.com/m-lab/epoxy-images/blob/0f675ac4f20b3a045bae579b348a472d54055cae/setup_stage3_coreos.sh#L62)):*
> ```Shell
>   # Commands adapted from:
>   #   https://kubernetes.io/docs/setup/independent/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl
>   RELEASE="$(curl -sSL https://dl.k8s.io/release/stable.txt | tee squashfs-root/share/oem/installed_k8s_version.txt)"
> ```

What will be the behavior if curl fails here? Would a sanity check on the RELEASE value help? Or something else?

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/52)*

**Comment by pboothe** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[setup_stage3_coreos.sh, line 6 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/52#-LC4ChI8DL8jtjGQuxKp:-LC4J_8w58HyGij-LkBi:b-896fix) ([raw file](https://github.com/m-lab/epoxy-images/blob/0f675ac4f20b3a045bae579b348a472d54055cae/setup_stage3_coreos.sh#L6)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please also note that we install dependencies for the current stable version of kubeadm (or k8s?)
</blockquote></details>

Done.

---

*[setup_stage3_coreos.sh, line 53 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/52#-LC4D9OPCH-JO2zxMcdc:-LC4JaLq-myAoNReJ54b:b-896fix) ([raw file](https://github.com/m-lab/epoxy-images/blob/0f675ac4f20b3a045bae579b348a472d54055cae/setup_stage3_coreos.sh#L53)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please use complete sentences in comments. I think I've inherited this bias from Go.
</blockquote></details>

Done.

---

*[setup_stage3_coreos.sh, line 56 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/52#-LC4DmAs8K95j5KNL6Z4:-LC4Jayp5tMOztelvLDk:b-896fix) ([raw file](https://github.com/m-lab/epoxy-images/blob/0f675ac4f20b3a045bae579b348a472d54055cae/setup_stage3_coreos.sh#L56)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This is a nit -- I still think long name parameters for less common options help readability. In this case `--location --show-error --silent` for curl and `--directory` for tar.
</blockquote></details>

Done.

---

*[setup_stage3_coreos.sh, line 62 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/52#-LC4Efvq7VhvCd4p0A5i:-LC4Jc-617XslHZBjay5:b-r1dkzm) ([raw file](https://github.com/m-lab/epoxy-images/blob/0f675ac4f20b3a045bae579b348a472d54055cae/setup_stage3_coreos.sh#L62)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What will be the behavior if curl fails here? Would a sanity check on the RELEASE value help? Or something else?
</blockquote></details>

The build will fail (thanks the the newly-added `set -euxo pipefail` at the top of this script), which is the right thing to happen.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/52)*

**Comment by pboothe** [comment]
PTAL. Travis is having issues, but it builds successfully on my machine, so I think it is worth reviewing. I will, of course, not merge until Travis passes.

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/52#-:-LC4aA_A4Wz6zwnroOZC:b-walwqu)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/52#-:-LC58ygs0yG3BgA3iCx3:bnfp4nl)*

**Comment by stephen-soltesz** [comment]
still :lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/52#-:-LC5QSdBEK8cwuocNjQa:b-5fsfav)*

**Pull request merged**
