### PR TITLE
Add generic builds for CoreOS images

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a `coreos-generic` directory with supporting scripts for generating a custom coreos image that can be used interchangeably on machines booted with epoxy.

This change includes rudimentary support for 

The approach outlined here is not the final word on how we will do this. Instead, it is an initial generic version that will enable us to continue building on CoreOS.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/7)

### CODE REVIEW

**Comment by pboothe** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[coreos-generic/resources/generate_network_config.sh, line 12 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/7#-L0oqz3vNMZqfW3fvHy-:-L0oqz3vNMZqfW3fvHy0:btzeuid) ([raw file](https://github.com/m-lab/epoxy-images/blob/54bfce11c218ab421adf6c71040c27c72716b668/coreos-generic/resources/generate_network_config.sh#L12)):*
> ```Shell
> #
> # For example:
> #   epoxy.ip=4.14.159.99::4.14.159.65:255.255.255.192:mlab3.lga0t.measurement-lab.org:eth0:off:8.8.8.8:8.8.4.4
> ```

Using : as a separator worries me when I start thinking about ipv6 compatibility. Can we use , instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/7)*

**Comment by pboothe** [comment]
Summarizing our conversation:

epoxy.ip should become three things:

epoxy.ipv4, epoxy.ipv6, and epoxy.net

However, it is also perfectly fine to push this code for now.

:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/7#-:-L0ozaqmnO9B2508sPVN:bu39rd1)*

**Comment by pboothe** [comment]
Oh! And the new variables should use command instead of colons.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/7#-:-L0ozsdeX4zjECnjNZG9:b95f8b0)*

**Comment by pboothe** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/7)*

**Comment by stephen-soltesz** [comment]
Thank you! I think we're good. I've written this up more explicitly as https://github.com/m-lab/epoxy/issues/7

I've referenced this issue in `generate_network_config.sh`.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/7#-:-L0p3mTu0c5Q_vZ0DvMz:b-qxlg9w)*

**Pull request merged**
