### PR TITLE
Add travis support for customized coreos images

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds support for building and deploying custom coreos images to travis.yml.

This change also includes related changes to `customize_coreos_pxe_image.sh` to accept specific coreos URLs and updates the travis submodule to the latest version so we can deploy_gcs.sh multiple source files.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/8)

### CODE REVIEW

**Comment by nkinkade** [comment]
Added a few small comments.

---

Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 26 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/8#-L0zwhNUA_nkVJyBHu2K:-L0zwhNVtnlz2WKgFQIo:b-r41wjt) ([raw file](https://github.com/m-lab/epoxy-images/blob/90dc68c41398454b88bb6a174be30c781a2be83a/.travis.yml#L26)):*
> ```YAML
> - set -e
> 
> - time docker build -t epoxy-images-builder . &> build.log || cat build.log
> ```

Nice... this new pattern of `&> log || cat log` is good!

---

*[.travis.yml, line 45 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/8#-L0zxIauaRcc2xxzOSyY:-L0zxIauaRcc2xxzOSyZ:b-dipkrm) ([raw file](https://github.com/m-lab/epoxy-images/blob/90dc68c41398454b88bb6a174be30c781a2be83a/.travis.yml#L45)):*
> ```YAML
>         http://stable.release.core-os.net/amd64-usr/1576.4.0/coreos_production_pxe.vmlinuz
>         http://stable.release.core-os.net/amd64-usr/1576.4.0/coreos_production_pxe_image.cpio.gz
>         /images/output/coreos_custom_pxe_image.cpio.gz &> /images/coreos.log" || cat coreos.log
> ```

Is there a missing double quote at the end of this line?

---

*[coreos-generic/customize_coreos_pxe_image.sh, line 38 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/8#-L0zyHYN5KETdSWf_d_P:-L0zyHYN5KETdSWf_d_Q:buzqaas) ([raw file](https://github.com/m-lab/epoxy-images/blob/90dc68c41398454b88bb6a174be30c781a2be83a/coreos-generic/customize_coreos_pxe_image.sh#L38)):*
> ```Shell
>   # Copy resources to the "/usr/share/oem" directory.
>   mkdir -p fake-usr/share/oem
>   cp -ar ${SCRIPTDIR}/resources/* fake-usr/share/oem/
> ```

Is `-r` redundant? Doesn't `-a` imply `-R`, which is a synonym of `-r`, I believe.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/8#-:-L0zyUv1BNjEQ-doowH0:b42udo5)*

**Comment by stephen-soltesz** [comment]
Review status: 2 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 26 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/8#-L0zwhNUA_nkVJyBHu2K:-L1--41j9-LMRTkXo-xF:bb6mt9b) ([raw file](https://github.com/m-lab/epoxy-images/blob/90dc68c41398454b88bb6a174be30c781a2be83a/.travis.yml#L26)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Nice... this new pattern of `&> log || cat log` is good!
</blockquote></details>

:+1:

---

*[.travis.yml, line 45 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/8#-L0zxIauaRcc2xxzOSyY:-L1--5XS6UfRW3Djg3H7:btd6nwb) ([raw file](https://github.com/m-lab/epoxy-images/blob/90dc68c41398454b88bb6a174be30c781a2be83a/.travis.yml#L45)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is there a missing double quote at the end of this line?
</blockquote></details>

My thinking here is that the command run by docker would create the log file, and if there is an error travis would cat the log file.

One of the original motives for this change was the 'write' errors coming from docker. This moves the text printing to travis so docker isn't involved at all.

---

*[coreos-generic/customize_coreos_pxe_image.sh, line 38 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/8#-L0zyHYN5KETdSWf_d_P:-L0zzmUPItgEQ52L48x_:bt9hqls) ([raw file](https://github.com/m-lab/epoxy-images/blob/90dc68c41398454b88bb6a174be30c781a2be83a/coreos-generic/customize_coreos_pxe_image.sh#L38)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is `-r` redundant? Doesn't `-a` imply `-R`, which is a synonym of `-r`, I believe.
</blockquote></details>

Good point. I meant to remove this altogether. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/8)*

**Comment by stephen-soltesz** [comment]
PTAL?

---

Review status: 2 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/8#-:-L1-G2BopXWs7oWPng6i:b-833305)*

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[.travis.yml, line 45 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/8#-L0zxIauaRcc2xxzOSyY:-L1-GQVTPoHtAdVyk5Xi:b-3kpi18) ([raw file](https://github.com/m-lab/epoxy-images/blob/90dc68c41398454b88bb6a174be30c781a2be83a/.travis.yml#L45)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

My thinking here is that the command run by docker would create the log file, and if there is an error travis would cat the log file.

One of the original motives for this change was the 'write' errors coming from docker. This moves the text printing to travis so docker isn't involved at all.
</blockquote></details>

That makes sense, though it is different from the way I did it yesterday for ndt-support:

https://github.com/m-lab/ndt-support/blob/master/.travis.yml#L15

Maybe the way it is handled in ndt-support is wrong? Perhaps it could have worked that way before I removed the `-t` flag?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/8#-:-L1-HHn9Meak2xgHr6Zt:bnfp4nl)*

**Comment by stephen-soltesz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[.travis.yml, line 45 at r1](https://reviewable.io:443/reviews/m-lab/epoxy-images/8#-L0zxIauaRcc2xxzOSyY:-L1-HX46XhFvaQudohhh:b-dsb10n) ([raw file](https://github.com/m-lab/epoxy-images/blob/90dc68c41398454b88bb6a174be30c781a2be83a/.travis.yml#L45)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

That makes sense, though it is different from the way I did it yesterday for ndt-support:

https://github.com/m-lab/ndt-support/blob/master/.travis.yml#L15

Maybe the way it is handled in ndt-support is wrong? Perhaps it could have worked that way before I removed the `-t` flag?
</blockquote></details>

Uff. You're right. The combination in ndt-support won't work the way we want. Even if there's an error, it will be hidden since there is not `-t` option to docker run. I should have caught that. We want to fix that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy-images/8)*

**Pull request merged**
