### PR TITLE
Updates base Ubuntu image from 20.04 to 22.04

### PR DESCRIPTION
**Pull request by nkinkade**
22.04 is the latest LTS release of Ubuntu.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/226)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
It's really that simple?

:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/226#-:-NFVGu5M7xxQ1mgAZyw7:bfois9d)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by nkinkade — COMMENTED** [review]
As far as I can tell, yes. The build finished and I rebooted mlab1-lga0t, logged in and then:

```
mlab@mlab1-lga0t:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

I was rather surprised, too, at how simple it was to jump between releases.  I looked over package version differences and they didn't see substantial, at least not for core packages we rely like `containerd`, for example, where both 20.04 and 22.04 are both using v1.5.9 but with different patch levels. The 20.04 kernel is 5.4.x and 22.04 is 5.15.x.

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/226#-:-NFVK_oB0ZK1ZZM2SpUG:bh30m6f)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
@mattmathis ^ which version of BBR is in Linux 5.15?

**Comment by nkinkade** [comment]
How does one even determine this? I see this:

https://github.com/torvalds/linux/commits/v5.15/net/ipv4/tcp_bbr.c

... and running `modinfo tcp_brr` shows this:

```
srcversion:     3B1BCEE47503FD816689638
```

... but I don't even know what that hash represents?

**Pull request merged**
