### PR TITLE
Updates packages in rootfs when building stage3 images

### LINKED ISSUE #213: Update packages on each build of stage3 Ubuntu image
The `debootstrap` utility can only source files from a single apt repository. In our case, when generating machine images we point it to the point release repository. What this means is that the images built by epoxy-images will only ever contain the packages at the versions they had at the time of the point release. For LTS releases of Ubuntu, this can mean we are running very old versions of packages, with known bugs which have been resolved in updates versions.

The OS is configured to automatically install security updates, but is not configured to install regular package updates. This is how we want it, but we need a mechanism to get updated packages from our base OS release onto the platform.

### PR DESCRIPTION
**Pull request by nkinkade**
This PR resolves #213.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/214)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/214)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[setup_stage3_ubuntu.sh, line 100 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/214#-Mq1CYQyARZym8dCpT9u:-Mq1CYQyARZym8dCpT9v:bbwce99) ([raw file](https://github.com/m-lab/epoxy-images/blob/a3a9a9939315fdda40d033a85313e0bc496819fc/setup_stage3_ubuntu.sh#L100)):*
> ```Shell
>     chroot $BOOTSTRAP apt-get update --fix-missing
> 
>     # Update all installed packages.
> ```

Please add a short note about why update is not enough. We evidently misunderstood how `update` worked originally, and it's still not obvious (from just this logic) why this is necessary. (the note is not for me but to help a future reader/updater understand that this step is critical).
___
*[setup_stage3_ubuntu.sh, line 104 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/214#-Mq1AxGuC8wJglc0IX8-:-Mq1AxGuC8wJglc0IX80:bqsfmr4) ([raw file](https://github.com/m-lab/epoxy-images/blob/a3a9a9939315fdda40d033a85313e0bc496819fc/setup_stage3_ubuntu.sh#L104)):*
> ```Shell
> 
>     # Install ipmitool to configure DRAC during stage1.
>     chroot $BOOTSTRAP apt-get install --yes ipmitool
> ```

:+1: (and thank you)
___
*[setup_stage3_ubuntu.sh, line 118 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/214#-Mq1CxCa29QUeEekgGmQ:-Mq1CxCa29QUeEekgGmR:bii8mo6) ([raw file](https://github.com/m-lab/epoxy-images/blob/a3a9a9939315fdda40d033a85313e0bc496819fc/setup_stage3_ubuntu.sh#L118)):*
> ```Shell
>     # Copy kernel image to output directory before removing it.
>     pushd $BOOTSTRAP/boot
>         cp $(ls -1 vmlinuz-* | tail -n1) ${OUTPUT_KERNEL}
> ```

Oooh, there are now multiple kernel versions b/c of the `dist-upgrade`?

Is `-1` necessary if the output is to a pipe?

Does `ls` guarantee the order of the results? Are we guaranteed to get the "latest" kernel version here?

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/214)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[setup_stage3_ubuntu.sh, line 100 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/214#-Mq1CYQyARZym8dCpT9u:-Mq1Jq5SEs1DaEROY9rr:b14s7z4) ([raw file](https://github.com/m-lab/epoxy-images/blob/a3a9a9939315fdda40d033a85313e0bc496819fc/setup_stage3_ubuntu.sh#L100)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a short note about why update is not enough. We evidently misunderstood how `update` worked originally, and it's still not obvious (from just this logic) why this is necessary. (the note is not for me but to help a future reader/updater understand that this step is critical).
</blockquote></details>

I don't believe there was a misunderstanding about how `update` worked/works. `update` does, and always has, just update the repository metadata to discover changes upstream, but it doesn't actually upgrade any packages on the machine. `upgrade` is the command that does that, which is why you often see this pattern in Debian based distros `apt-get update && apt-get upgrade`. This doesn't seem like  the right place to add documentation for how `apt` works. Do you disagree?
___
*[setup_stage3_ubuntu.sh, line 118 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/214#-Mq1CxCa29QUeEekgGmQ:-Mq1Keft0M61H0MGoale:bw01ovx) ([raw file](https://github.com/m-lab/epoxy-images/blob/a3a9a9939315fdda40d033a85313e0bc496819fc/setup_stage3_ubuntu.sh#L118)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Oooh, there are now multiple kernel versions b/c of the `dist-upgrade`?

Is `-1` necessary if the output is to a pipe?

Does `ls` guarantee the order of the results? Are we guaranteed to get the "latest" kernel version here?
</blockquote></details>

Yeah, the kernel gets updates too, since it's just a package like anything else, and this may cause multiple kernels to live on the system. 

Oh, you are right. The `-1` flag is indeed unnecessary because of the pipe.  As far as I know the default sort order for `ls` is alphabetical. , and I was thinking that kernels named like `vmlinuz-5.4.0-26-generic`, `vmlinuz-5.4.0-91-generic`, etc. would always alphabetically sort  in a way such that the newest one would come last. I suppose I could `ls -v` to do a "version" sorted list, just to be sure?

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/214)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[setup_stage3_ubuntu.sh, line 100 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/214#-Mq1CYQyARZym8dCpT9u:-Mq1NgNS3mxd7J1nmC10:bmigoq2) ([raw file](https://github.com/m-lab/epoxy-images/blob/a3a9a9939315fdda40d033a85313e0bc496819fc/setup_stage3_ubuntu.sh#L100)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I don't believe there was a misunderstanding about how `update` worked/works. `update` does, and always has, just update the repository metadata to discover changes upstream, but it doesn't actually upgrade any packages on the machine. `upgrade` is the command that does that, which is why you often see this pattern in Debian based distros `apt-get update && apt-get upgrade`. This doesn't seem like  the right place to add documentation for how `apt` works. Do you disagree?
</blockquote></details>

:) I don't want documentation for apt -- I'm requesting a description of our use case that requires this functionality.

The `update` command precedes a comment that says "Update" but runs `dist-upgrade`.

If I'm being too much of a stickler please push back. I missed this originally. I'm trying to add breadcrumbs to help whoever is next not miss a similar thing.
___
*[setup_stage3_ubuntu.sh, line 118 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/214#-Mq1CxCa29QUeEekgGmQ:-Mq1O71x06M0iwUTb9rj:byt1gui) ([raw file](https://github.com/m-lab/epoxy-images/blob/a3a9a9939315fdda40d033a85313e0bc496819fc/setup_stage3_ubuntu.sh#L118)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Yeah, the kernel gets updates too, since it's just a package like anything else, and this may cause multiple kernels to live on the system. 

Oh, you are right. The `-1` flag is indeed unnecessary because of the pipe.  As far as I know the default sort order for `ls` is alphabetical. , and I was thinking that kernels named like `vmlinuz-5.4.0-26-generic`, `vmlinuz-5.4.0-91-generic`, etc. would always alphabetically sort  in a way such that the newest one would come last. I suppose I could `ls -v` to do a "version" sorted list, just to be sure?
</blockquote></details>

How might `vmlinuz-5.4.0-26-generic` and `vmlinuz-5.10.0-26-generic` be sorted alphabetically?

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/214)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[setup_stage3_ubuntu.sh, line 100 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/214#-Mq1CYQyARZym8dCpT9u:-Mq1Ri_T62IV8BKACMpO:b-j3d15k) ([raw file](https://github.com/m-lab/epoxy-images/blob/a3a9a9939315fdda40d033a85313e0bc496819fc/setup_stage3_ubuntu.sh#L100)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

:) I don't want documentation for apt -- I'm requesting a description of our use case that requires this functionality.

The `update` command precedes a comment that says "Update" but runs `dist-upgrade`.

If I'm being too much of a stickler please push back. I missed this originally. I'm trying to add breadcrumbs to help whoever is next not miss a similar thing.
</blockquote></details>

Okay. I made a tiny change to the comments. Satisfied now!!!! ;)
___
*[setup_stage3_ubuntu.sh, line 118 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/214#-Mq1CxCa29QUeEekgGmQ:-Mq1RqMw9qGxnJwLsH3H:b4ke860) ([raw file](https://github.com/m-lab/epoxy-images/blob/a3a9a9939315fdda40d033a85313e0bc496819fc/setup_stage3_ubuntu.sh#L118)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

How might `vmlinuz-5.4.0-26-generic` and `vmlinuz-5.10.0-26-generic` be sorted alphabetically?
</blockquote></details>

True. I've added the `-v` flag to `ls`.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: - with one comment.

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/214#-:-Mq1CJLq0B1sIRQUo1g4:bbqfuip)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[setup_stage3_ubuntu.sh, line 100 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/214#-Mq1CYQyARZym8dCpT9u:-Mq1SwOsAndiXKDsHF7J:bav6mgs) ([raw file](https://github.com/m-lab/epoxy-images/blob/a3a9a9939315fdda40d033a85313e0bc496819fc/setup_stage3_ubuntu.sh#L100)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Okay. I made a tiny change to the comments. Satisfied now!!!! ;)
</blockquote></details>

I think I was looking for a statement on the expected behavior / requirements. And, taking a step back, that is exactly what the header comment of the script is for. Added a comment there. THEN IT LGTM!! :D
___
*[setup_stage3_ubuntu.sh, line 4 at r2](https://reviewable.io/reviews/m-lab/epoxy-images/214#-Mq1SftE9VByOzAB4HVp:-Mq1SftE9VByOzAB4HVq:b-ulol5a) ([raw file](https://github.com/m-lab/epoxy-images/blob/3d0fc228fcd11a8f339897ed6ec8f9b86c837cc4/setup_stage3_ubuntu.sh#L4)):*
> ```Shell
> #
> # setup_stage3_ubuntu.sh builds an initram image based on the Ubuntu Focal
> # (20.04) OS, that includes M-Lab configs and scripts, epoxy_client and k8s-related binaries
> ```

Ubuntu Focal (20.04) OS "with all package upgraded to their latest versions".

**Review by nkinkade — COMMENTED** [review]
Fixed. Thank you.

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/214#-:-Mq1WJ5TEfMvDFFnQKOd:b-1jl00q)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[setup_stage3_ubuntu.sh, line 4 at r2](https://reviewable.io/reviews/m-lab/epoxy-images/214#-Mq1SftE9VByOzAB4HVp:-Mq1WFJj95XRQ-Luqx5h:b-896fix) ([raw file](https://github.com/m-lab/epoxy-images/blob/3d0fc228fcd11a8f339897ed6ec8f9b86c837cc4/setup_stage3_ubuntu.sh#L4)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Ubuntu Focal (20.04) OS "with all package upgraded to their latest versions".
</blockquote></details>

Done.

**Pull request merged**
